// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEDb8Fv43ncF_baa1x9RIWzY1Z6U4Io90',
    appId: '1:951448989185:web:58bd4853f49c24af4a9a00',
    messagingSenderId: '951448989185',
    projectId: 'fir-7d6e9',
    authDomain: 'fir-7d6e9.firebaseapp.com',
    storageBucket: 'fir-7d6e9.firebasestorage.app',
    measurementId: 'G-PZW9SVVJPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyPQyFBqr3ikQNpOC8HngehbUeDbpAFCE',
    appId: '1:951448989185:android:7cbcf021f72005384a9a00',
    messagingSenderId: '951448989185',
    projectId: 'fir-7d6e9',
    storageBucket: 'fir-7d6e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSy1UTR5hCee6ZxFxf1itffXmQdebIQsQ',
    appId: '1:951448989185:ios:11aa7d776b9e352c4a9a00',
    messagingSenderId: '951448989185',
    projectId: 'fir-7d6e9',
    storageBucket: 'fir-7d6e9.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSy1UTR5hCee6ZxFxf1itffXmQdebIQsQ',
    appId: '1:951448989185:ios:11aa7d776b9e352c4a9a00',
    messagingSenderId: '951448989185',
    projectId: 'fir-7d6e9',
    storageBucket: 'fir-7d6e9.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEDb8Fv43ncF_baa1x9RIWzY1Z6U4Io90',
    appId: '1:951448989185:web:45b0ca6cdc599f044a9a00',
    messagingSenderId: '951448989185',
    projectId: 'fir-7d6e9',
    authDomain: 'fir-7d6e9.firebaseapp.com',
    storageBucket: 'fir-7d6e9.firebasestorage.app',
    measurementId: 'G-T5132MBY6S',
  );
}
